### ISSUE TITLE
PDDocument.load（）加载文件流错误

### ISSUE THREAD

**Issue by xayo69** [HPInc/jipp#190]
java.lang.ExceptionInInitializerError
at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1099)

Caused by: java.lang.IllegalArgumentException: awt.163
at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:720)

**Comment by HPNavjot** [comment]
@xayo69  could you please more information on the crash.

Example: 
- Steps to reproduce this issue
- Which method from this library you are using when facing this exception
- Frequency of crash
Feel free to add logs if possible.
