### ISSUE TITLE
Exotic input streams cause parse errors

### ISSUE THREAD

**Issue by GladeDiviney** [HPInc/jipp#71]
```
com.hp.jipp.util.ParseError: Value too short: expected 28 but got 25
	at com.hp.jipp.encoding.IppInputStream.readValueBytes$jipp_core(IppInputStream.kt:42)
	at com.hp.jipp.encoding.IppInputStream.readString$jipp_core(IppInputStream.kt:63)
	at com.hp.jipp.encoding.KeywordType$$special$$inlined$invoke$1.readValue(Codec.kt:55)
	at com.hp.jipp.encoding.AttributeGroup$Companion.readValue(AttributeGroup.kt:211)
	at com.hp.jipp.encoding.AttributeGroup$Companion.readNextValue(AttributeGroup.kt:230)
```

Caused by using `read(byte[])` (which may well decide to return early without blocking for additional bytes) instead of `readFully(byte[])` (which will not).

**Comment by tushar1402** [comment]
Hi Jipp team,

We are running a load test for our print path service which is built on top of IPP. We are using jipp library for different operations, when we are doing packet conversion to binary, after some requests are sent to server, we are getting EOF exception.

We are using 0.6.21 version of jipp currently for our testing, and we are observing this issue. Could you please help us understand how can we handle this issue?

We are using Jmeter as our load testing tool and request body is byteArray after converting the IPP packet. In Jmeter we are handling the exception also but from server side we are seeing this error being thrown from the service when load is generated.
